specVersion: 0.2.0
name: lesson3
version: 1.0.0
description: lesson4
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3'
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: 'https://api.subquery.network/sq/subquery/dictionary-polkadot'
dataSources:
  - kind: substrate/Runtime
    # startBlock: for testing
    # https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/explorer/query/8099664
    startBlock: 8099663
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleStackingEvent
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Rewarded
        - handler: handleStackingEvent
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleBlock
          kind: substrate/BlockHandler